### ISSUE TITLE
If you right click any block (in aether) with ambrosium, it will change to Enchanted Aether Grass

### ISSUE THREAD

**Issue by blacklambCZ** [Gilded-Games/The-Aether-Archived#124] opened 2021-04-13 17:22 UTC
Hello, so i played The Aether. latest update v1.5.3.1 And there is a bug with ambrosium that if you right click any block in the aether dimension (including non-aether blocks, but only in aether dimension) it will change to Enchanted Aether Grass:
https://www.youtube.com/watch?v=feVeo6_DXlk
(I discovered it in my hardcore world when i healed my health with ambrosium.)
Fix it please :)
And for those who wants to use it, use it as fast as possible its little bit OP

**Comment by OzPayn** [comment] 2021-04-13 17:32
So far unable to reproduce this one, could you list your installed mods and configs?

**Comment by blacklambCZ** [comment] 2021-04-13 19:45
Mods: The Aether and Just Enough Items. (Turning Off JEI doesnt fix the issue. heres config:
![2021-04-13_21 43 27](https://user-images.githubusercontent.com/76792760/114611515-6c905c80-9ca1-11eb-898a-854f69464367.png)
![2021-04-13_21 43 30](https://user-images.githubusercontent.com/76792760/114611519-6d28f300-9ca1-11eb-9918-f8d952761da4.png)
![2021-04-13_21 43 33](https://user-images.githubusercontent.com/76792760/114611521-6d28f300-9ca1-11eb-93e3-3ffb46baf8bd.png)
![2021-04-13_21 43 36](https://user-images.githubusercontent.com/76792760/114611523-6dc18980-9ca1-11eb-9b05-363fa51f9ec4.png)
![2021-04-13_21 43 44](https://user-images.githubusercontent.com/76792760/114611526-6dc18980-9ca1-11eb-8b17-af4f15c29014.png)
![2021-04-13_21 44 47](https://user-images.githubusercontent.com/76792760/114611589-7f0a9600-9ca1-11eb-987b-98224254bfa1.png)

**Comment by blacklambCZ** [comment] 2021-04-13 19:45
also, sorry for late response, i was doing something.

**Comment by blacklambCZ** [comment] 2021-04-13 20:03
in 1.12.2.v1.5.3 the glitch appeared. i tried now running different versions of The Aether, and the bug started there. 1.7.10 hasnt that bug.

**Comment by blacklambCZ** [comment] 2021-04-13 20:16
I dont know what causes it. but i found out that you cant use ambrosium in overworld on Aether Grass or anything (so the glitch works only in The Aether Dimension.)  Even Aether Grass will not be enchanted in the overworld. So maybe a code was changed, so instead that it can be used on Aether Grass. there may be someone who wanted to not have ability to enchant the Aether Grass in other dimensions, but when he did it. it broke and made every block in The Aether Enchantable. (EDIT: i also trying it on my server to test if it works there. And yea, works on servers too.)

**Comment by Zachary2897** [comment] 2021-04-15 03:35
Appears to have been fixed in [this commit](https://github.com/Gilded-Games/The-Aether-Archived/commit/8adb9347a39638fca3024735e6aafc2d7ca0453c), the fix just hasn't been released to CurseForge yet.

In the meantime, I've made a CraftTweaker script which fixes this (although it doesn't fix the issue where Ambrosium can't be used in the Overworld):
```
events.onPlayerInteractBlock(function(event as crafttweaker.event.PlayerInteractBlockEvent) {
	if (!isNull(event.item) && !isNull(event.block) && event.item.definition.id == "aether_legacy:ambrosium_shard" && event.block.definition.id != "aether_legacy:aether_grass") {
		event.cancel();
	}
});
```

**Comment by blacklambCZ** [comment] 2021-04-15 05:44
Hello, so i need to use CraftTweaker mod to use the script right?

**Comment by blacklambCZ** [comment] 2021-04-15 05:59
(i never used CraftTweaker so i dont know how to add the script)

**Comment by Zachary2897** [comment] 2021-04-15 12:59
Once you've added CraftTweaker, save the script as a .zs file (for example, "ambrosium_fix.zs" or something similar) and add it to a folder called "scripts" in the same directory as the "mods" folder.

**Comment by blacklambCZ** [comment] 2021-04-15 18:53
It worked. Thanks!

**Comment by bconlon1** [comment] 2021-04-16 18:15
Just gonna close this since as mentioned it is fixed in a commit I just haven't gotten around to releasing a build with the fix.

**Closed as completed by bconlon1** 2021-04-16 18:15 UTC
